/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardTestimonialsRouteImport } from './routes/_authenticated/dashboard.testimonials'
import { Route as AuthenticatedDashboardProjectsRouteImport } from './routes/_authenticated/dashboard.projects'
import { Route as AuthenticatedDashboardMediaRouteImport } from './routes/_authenticated/dashboard.media'
import { Route as AuthenticatedDashboardLeadsRouteImport } from './routes/_authenticated/dashboard.leads'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard.categories'
import { Route as AuthenticatedDashboardBlogsRouteImport } from './routes/_authenticated/dashboard.blogs'
import { Route as AuthenticatedDashboardProjectsIndexRouteImport } from './routes/_authenticated/dashboard.projects.index'
import { Route as AuthenticatedDashboardProjectsNewRouteImport } from './routes/_authenticated/dashboard.projects.new'
import { Route as AuthenticatedDashboardProjectsIdRouteImport } from './routes/_authenticated/dashboard.projects.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTestimonialsRoute =
  AuthenticatedDashboardTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectsRoute =
  AuthenticatedDashboardProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMediaRoute =
  AuthenticatedDashboardMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLeadsRoute =
  AuthenticatedDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBlogsRoute =
  AuthenticatedDashboardBlogsRouteImport.update({
    id: '/blogs',
    path: '/blogs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectsIndexRoute =
  AuthenticatedDashboardProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardProjectsRoute,
  } as any)
const AuthenticatedDashboardProjectsNewRoute =
  AuthenticatedDashboardProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardProjectsRoute,
  } as any)
const AuthenticatedDashboardProjectsIdRoute =
  AuthenticatedDashboardProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/dashboard/blogs': typeof AuthenticatedDashboardBlogsRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRouteWithChildren
  '/dashboard/testimonials': typeof AuthenticatedDashboardTestimonialsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/dashboard/projects/new': typeof AuthenticatedDashboardProjectsNewRoute
  '/dashboard/projects/': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/dashboard/blogs': typeof AuthenticatedDashboardBlogsRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/dashboard/testimonials': typeof AuthenticatedDashboardTestimonialsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/dashboard/projects/new': typeof AuthenticatedDashboardProjectsNewRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authenticated/dashboard/blogs': typeof AuthenticatedDashboardBlogsRoute
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/_authenticated/dashboard/media': typeof AuthenticatedDashboardMediaRoute
  '/_authenticated/dashboard/projects': typeof AuthenticatedDashboardProjectsRouteWithChildren
  '/_authenticated/dashboard/testimonials': typeof AuthenticatedDashboardTestimonialsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/_authenticated/dashboard/projects/new': typeof AuthenticatedDashboardProjectsNewRoute
  '/_authenticated/dashboard/projects/': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/consultation'
    | '/contact'
    | '/login'
    | '/services'
    | '/dashboard'
    | '/projects/$slug'
    | '/projects/'
    | '/dashboard/blogs'
    | '/dashboard/categories'
    | '/dashboard/leads'
    | '/dashboard/media'
    | '/dashboard/projects'
    | '/dashboard/testimonials'
    | '/dashboard/'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/consultation'
    | '/contact'
    | '/login'
    | '/services'
    | '/projects/$slug'
    | '/projects'
    | '/dashboard/blogs'
    | '/dashboard/categories'
    | '/dashboard/leads'
    | '/dashboard/media'
    | '/dashboard/testimonials'
    | '/dashboard'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/consultation'
    | '/contact'
    | '/login'
    | '/services'
    | '/_authenticated/dashboard'
    | '/projects/$slug'
    | '/projects/'
    | '/_authenticated/dashboard/blogs'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/leads'
    | '/_authenticated/dashboard/media'
    | '/_authenticated/dashboard/projects'
    | '/_authenticated/dashboard/testimonials'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/projects/$id'
    | '/_authenticated/dashboard/projects/new'
    | '/_authenticated/dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogsRoute: typeof BlogsRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/testimonials': {
      id: '/_authenticated/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof AuthenticatedDashboardTestimonialsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projects': {
      id: '/_authenticated/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/media': {
      id: '/_authenticated/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof AuthenticatedDashboardMediaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/leads': {
      id: '/_authenticated/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/blogs': {
      id: '/_authenticated/dashboard/blogs'
      path: '/blogs'
      fullPath: '/dashboard/blogs'
      preLoaderRoute: typeof AuthenticatedDashboardBlogsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projects/': {
      id: '/_authenticated/dashboard/projects/'
      path: '/'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectsRoute
    }
    '/_authenticated/dashboard/projects/new': {
      id: '/_authenticated/dashboard/projects/new'
      path: '/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectsRoute
    }
    '/_authenticated/dashboard/projects/$id': {
      id: '/_authenticated/dashboard/projects/$id'
      path: '/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectsRoute
    }
  }
}

interface AuthenticatedDashboardProjectsRouteChildren {
  AuthenticatedDashboardProjectsIdRoute: typeof AuthenticatedDashboardProjectsIdRoute
  AuthenticatedDashboardProjectsNewRoute: typeof AuthenticatedDashboardProjectsNewRoute
  AuthenticatedDashboardProjectsIndexRoute: typeof AuthenticatedDashboardProjectsIndexRoute
}

const AuthenticatedDashboardProjectsRouteChildren: AuthenticatedDashboardProjectsRouteChildren =
  {
    AuthenticatedDashboardProjectsIdRoute:
      AuthenticatedDashboardProjectsIdRoute,
    AuthenticatedDashboardProjectsNewRoute:
      AuthenticatedDashboardProjectsNewRoute,
    AuthenticatedDashboardProjectsIndexRoute:
      AuthenticatedDashboardProjectsIndexRoute,
  }

const AuthenticatedDashboardProjectsRouteWithChildren =
  AuthenticatedDashboardProjectsRoute._addFileChildren(
    AuthenticatedDashboardProjectsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBlogsRoute: typeof AuthenticatedDashboardBlogsRoute
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardLeadsRoute: typeof AuthenticatedDashboardLeadsRoute
  AuthenticatedDashboardMediaRoute: typeof AuthenticatedDashboardMediaRoute
  AuthenticatedDashboardProjectsRoute: typeof AuthenticatedDashboardProjectsRouteWithChildren
  AuthenticatedDashboardTestimonialsRoute: typeof AuthenticatedDashboardTestimonialsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBlogsRoute: AuthenticatedDashboardBlogsRoute,
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardLeadsRoute: AuthenticatedDashboardLeadsRoute,
    AuthenticatedDashboardMediaRoute: AuthenticatedDashboardMediaRoute,
    AuthenticatedDashboardProjectsRoute:
      AuthenticatedDashboardProjectsRouteWithChildren,
    AuthenticatedDashboardTestimonialsRoute:
      AuthenticatedDashboardTestimonialsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogsRoute: BlogsRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
